language: common-lisp
sudo: false

addons:
  apt:
    packages:
      - libc6-i386
      - openjdk-7-jre

env:
  global:
    - PATH=~/.roswell/bin:$PATH
    - ROSWELL_INSTALL_DIR=$HOME/.roswell
  matrix:
    - LISP=abcl-bin
    # - LISP=allegro
    - LISP=ccl-bin
    #- LISP=clasp
    - LISP=clisp
    - LISP=cmu-bin
    - LISP=ecl
    #- LISP=mkcl
    - LISP=sbcl-bin

# matrix:
#   allow_failures:
#     - env: LISP=clisp
#     - env: LISP=abcl
#     - env: LISP=ecl
#     - env: LISP=cmucl
#     - env: LISP=alisp

install:
  - curl -L https://raw.githubusercontent.com/roswell/roswell/release/scripts/install-for-ci.sh | sh

cache:
  directories:
    - $HOME/.roswell
    - $HOME/.config/common-lisp

script:
  - ros run -e '(pushnew :literate-test *features*)'
            -e '(ql:quickload :literate-lisp)'
            -e '(literate-lisp:with-literate-syntax (load "./tangle.org"))'
            -e '(ql:quickload :literate-demo)'
            -e '(if (not (literate-lisp::run-test)) (uiop:quit 1))'
            -e '(if (not (literate-demo::run-test)) (uiop:quit 1))'
            -e '(uiop:quit 0)'
            
