
name: Continous Integration
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        LISP: [abcl-bin, ccl-bin, cmu-bin, ecl, sbcl-bin]
    steps:
    - uses: actions/checkout@v1
    - name: install Lisp
      env:
        LISP: ${{matrix.LISP}}
      run: |
        export PATH=~/.roswell/bin:$PATH
        export ROSWELL_INSTALL_DIR=$HOME/.roswell
        curl -L https://raw.githubusercontent.com/roswell/roswell/release/scripts/install-for-ci.sh | sh
    - name: run test
      run: |
        export PATH=~/.roswell/bin:$PATH
        ros run -e '(pushnew :lilith-test *features*)'\
                -e '(load "../lilith.asd")'\
                -e '(ql:quickload :fiveam)'\
                -e '(asdf::oos (quote asdf:load-op) :lilith)'\
                -e '(push :literate-test *features*)'\
                -e '(compile-file "../lilith.org")'\
                -e '(load "../lilith.org")'\
                -e '(if (not (lilith::run-test))(uiop:quit 1))'\
                -e '(uiop:quit 0)'
